"""In-game messages"""
"""Combat Prompts:
"You have been challenged by {}!"
"{} sent out {} Morty!"
"What will you do?"
"Waiting for opponent..."
"The foe's {} Morty used {}!"
"Your {} Morty used {}!"
"It's sensational!"
"It's pathetic!"
"{} Morty is dazed!"
"Would you like to switch your Morty?"
"Select a Morty."
"What would you like to do?"
"Your {} has been paralyzed!"
"Your {} has been poisoned!"
"The foe's {} Morty's {} fell!"
"Your {} Morty's {} grew!"
"The foe's {} Morty's {} fell!"
"Your {} Morty's {} fell!"
"{} sent out {} Morty!"
"You defeated {}!"
"{} defeated you!"
"""
